# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://arclps.github.io
date_format: "ordinal"
title: "mmmmmpasto"
subtitle: "subtítulo"
description: "descripción"
keywords: #
encoding: "utf-8"
repository: arclps/arclps.github.io
# 对 css 和 js 资源的 cdn 加速配置
#cdn:
#    jsdelivr:
#        enabled: true
# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: false
        hide-platforms: qq,facebook
    # 不蒜子访问统计
    busuanzi:
        enabled: false
        start_date: 2020-05-03
    # My Popular Repositories
    side_bar_repo:
        enabled: true
        limit: 5
    # 文章字数统计
    word_count:
        enabled: true
    
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: arclps
organization: 
organization_url: 
github_username: arclps
location: #
email: # @gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Inicio

  -
    href: /archivo/
    label: Archivo

#   -
#     href: /open-source/
#     label: 开源

  -
    href: /links/
    label: Links

#  -
#    href: /about/
#    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 5
lsi: false
quiet: false
excerpt_separator: "\n\n"
#permalink: /:year/:month/:day/:title/
permalink: /:title/
plugins:
#    - jekyll-github-metadata
#    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
#     - jekyll-mentions
#collections:
#    wiki:
#        output: true
#        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours

# https://utteranc.es/
utterances:
    repo: mzlogin/blog-comments
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-1
    adsense:
        footer: true
        sidebar: true 
        sidebar-detail: true 
        content_header: false
        content_footer: false
